# Pre-commit hooks configuration
# Install with: pip install pre-commit && pre-commit install

repos:
  - repo: local
    hooks:
      - id: swift-format
        name: swift-format
        entry: swift-format
        args: ["-i"]
        language: system
        files: \.swift$
        pass_filenames: true

      - id: swiftlint
        name: SwiftLint
        entry: swiftlint
        args: ["--fix", "--config", ".swiftlint.yml"]
        language: system
        files: \.swift$
        pass_filenames: true

      - id: no-commit-to-main
        name: Don't commit to main
        entry: bash -c 'if [ "$1" = "main" ]; then echo "Direct commits to main branch are not allowed"; exit 1; fi' --
        language: system
        pass_filenames: false
        always_run: true
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: \.md$
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: mixed-line-ending
        args: ['--fix=lf']
