# SwiftLint Configuration
# Based on Google Swift Style Guide
# https://google.github.io/swift/

# Paths to include
included:
  - Sources
  - Tests
  - Benchmarks

# Paths to exclude
excluded:
  - .build
  - .swiftpm
  - Package.swift
  - ${PWD}/.build

# Enabled rules beyond default
opt_in_rules:
  # Readability
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fallthrough
  - fatal_error_message
  # - file_header  # Disabled for now
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

  # Performance
  - array_init
  - discouraged_object_literal
  - enum_case_associated_values_count
  - reduce_into

  # Style (Google-specific)
  - closure_parameter_position
  - implicit_getter
  - number_separator
  - object_literal
  - operator_whitespace
  - prefer_self_in_static_references
  - sorted_imports
  - trailing_comma
  - type_contents_order
  - unused_import
  - vertical_whitespace_between_cases

# Disabled rules (conflicts with Google style)
disabled_rules:
  - trailing_whitespace  # Google allows trailing whitespace in some cases
  - todo  # TODOs are allowed
  - line_length  # We'll configure this differently
  - file_length
  - type_body_length
  - function_body_length
  - cyclomatic_complexity
  - force_cast
  - force_try

# Rule configurations
analyzer_rules:
  - unused_declaration
  - unused_import

# Custom configurations
line_length:
  warning: 100
  error: 120
  ignores_urls: true
  ignores_function_declarations: false
  ignores_comments: true
  ignores_interpolated_strings: true

# Identifier naming (Google style)
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - ID
    - URL
    - url
    - to
    - by
    - at
    - in
    - on
    - or
    - as
    - is
    - of
    - up
    - i
    - j
    - k
    - x
    - y
    - z
    - r
    - g
    - b
    - a

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
  allowed_symbols: ["_"]
  validates_start_with_lowercase: false  # Types start with uppercase

function_parameter_count:
  warning: 6
  error: 8

# Nesting (Google recommends shallow nesting)
nesting:
  type_level: 2
  function_level: 3

# File header (Google requires copyright headers)
# Disabled for now - can be enabled with specific pattern later
# file_header:
#   required_pattern: |
#     \/\/
#     \/\/ .*\.swift
#     \/\/ SwiftMessageBus
#     \/\/

# Type contents order (Google specific ordering)
type_contents_order:
  order:
    - case
    - associated_type
    - type_alias
    - subtype
    - type_property
    - instance_property
    - ib_inspectable
    - ib_outlet
    - initializer
    - type_method
    - view_life_cycle_method
    - ib_action
    - other_method
    - subscript
    - deinitializer

# Attributes (Google style)
attributes:
  always_on_same_line:
    - "@IBAction"
    - "@NSManaged"
    - "@objc"
    - "@nonobjc"
    - "@IBOutlet"
    - "@IBInspectable"
    - "@GKInspectable"
  always_on_line_above:
    - "@available"
    - "@discardableResult"
    - "@UIApplicationMain"
    - "@NSApplicationMain"
    - "@main"
    - "@MainActor"
    - "@Sendable"

# Multiline arguments (Google style)
multiline_arguments:
  first_argument_location: next_line
  only_enforce_after_first_closure_on_first_line: true

# Multiline parameters (Google style)
multiline_parameters:
  max_number_of_retries: 2

# Modifier order (Google style)
modifier_order:
  preferred_modifier_order:
    - acl
    - setterACL
    - override
    - dynamic
    - mutating
    - nonmutating
    - convenience
    - typeMethods
    - owned
    - final
    - required
    - optional
    - lazy
    - transient
    - weak

# Trailing comma (Google requires trailing commas in multiline)
trailing_comma:
  mandatory_comma: true

# Vertical whitespace
vertical_whitespace:
  max_empty_lines: 2

# Number separator (Google style: underscores for readability)
number_separator:
  minimum_length: 5
  minimum_fraction_length: 5
  exclude_ranges: true

# Empty count
empty_count:
  severity: warning

# Sorted imports
sorted_imports:
  groups:
    - [[testable], [module]]
    - [submodule]

# Custom rules
custom_rules:
  # Prefer struct over class when possible
  prefer_struct:
    name: "Prefer Struct"
    regex: "^class\\s+\\w+[^\\{]*\\{"
    message: "Consider using a struct instead of a class when possible"
    severity: warning

  # Space after comment slashes
  comment_spacing:
    name: "Comment Spacing"
    regex: "//[^ /\\n]"
    message: "Add a space after // in comments"
    severity: warning

  # No print statements in production code
  no_print:
    name: "No Print Statements"
    regex: "\\bprint\\("
    message: "Remove print statements from production code"
    severity: warning
    excluded:
      - "Tests/*"
      - "Benchmarks/*"

# Reporter type
reporter: "xcode"
